<?php 
$this->setTitle('Accueil');
$this->setDescription('Page d\'Acceuil du site');
?>

<div class="container">
    
    <h3>Gestion d'un espace membre</h3>

    <h3> S'enregistrer dans la base de données </h3>
<form class="form-horizontal" action = "index.php" method = "post"> 

    <div class="form-group"> 
        <label for="inputprenom" class = "control-label col-xs-2"> Prenom : </label>
        <div class = "col-xs-6">
            <input type="text" id="inputprenom" name="prenom" value="<?=$prenom?>">
            <p class ="message" > <?= $messageprenom;?> </p>
        </div>

        <label for="inputnom" class = "control-label col-xs-2"> Nom : </label>
        <div class = "col-xs-6">
            <input type="text" id="inputnom" name="nom" value="<?=$nom?>" >
            <p class ="message" > <?= $messagenom;?> </p>
        </div>

        <label for="inputlogin" class = "control-label col-xs-2"> Login : </label>
        <div class = "col-xs-6">
            <input type="text" id="inputlogin" name="login" value="<?=$login?>" >
            <p class ="message" > <?= $messagelogin;?> </p>
        </div>
 
        <label for="inputpassword" class = "control-label col-xs-2"> Mot de Passe : </label>
        <div class = "col-xs-6">
            <input type="password" id="inputpassword" name="password" value="" >
            <p class ="message" > <?= $messagepass;?> </p>
        </div>
    </div> 

<input type="submit" class ="col-xs-2 col-xs-offset-3 btn btn-success" value = "S'inscrire"/>
</form><br>

<div class = 'messageok has-success' >
<h3><?=$messageok;?></h3>
</div>

<h3> Se connecter </h3>
<form class="form-horizontal" action = "index.php" method = "post"> 

    <div class="form-group"> 
        <label for="inputloginrech" class = "control-label col-xs-2"> Login : </label>
        <div class = "col-xs-6">
            <input type="text" id="inputloginrech" name="loginrech" value="<?=$loginrech?>">
            <p class ="message" > <?= $messageloginrech;?> </p>
        </div>
    </div> 

    <div class="form-group"> 
        <label for="inputpasswordrech" class = "control-label col-xs-2"> Password : </label>
        <div class = "col-xs-6">
            <input type="text" id="inputpasswordrech" name="passwordrech" value="" >
            <p class ="message" > <?= $messagepassrech;?> </p>
        </div>
    </div> 

<input type="submit" class ="col-xs-2 col-xs-offset-3 btn btn-warning" value = "Connexion"/>
</form><br>

    <div class="messageok has-success">
    <h3><?=$message;?></h3>
    </div>
    
</div> <!-- Container -->

