<?php 
$this->setTitle('Accueil');
$this->setDescription('Page d\'Acceuil du site');
?>

<div class="container">
    
    <h3>Gestion d'un espace membre</h3>

<a href="enregistrement"><button class= "btn btn-success">S'enregistrer</button></a>

<h3> Se connecter </h3>
<form class="form-horizontal" method = "post" action = "connexion">
<?php echo $this->test;?>
<?php echo $this->form->input('emaillogin','Email'); ?>
<?php echo $this->form->input('mdplogin','Mot de passe',array('type'=>'password')); ?>


<input type="submit" class ="col-xs-2 col-xs-offset-3 btn btn-warning" value = "Connexion"/>

</form><br>

</div> <!-- Container -->

